#!/usr/bin/env python3
"""
This module provides an asynchronous function to collect random numbers
generated by an asynchronous generator and return them as a list.
"""

from typing import List  # Import typing for type annotations
import importlib  # Import the importlib module to handle dynamic imports

# Using importlib allows us to import a module with a non-standard name
async_generator = importlib.import_module("0-async_generator").async_generator


# Define an asynchronous function that collects 10 random numbers
async def async_comprehension() -> List[float]:
    """
    Asynchronously collects 10 random numbers generated by async_generator
    and returns them as a list.

    Returns:
        List[float]: A list of 10 random floating-point numbers.
    """
    # Use an async comprehension to collect numbers from async_generator
    return [number async for number in async_generator()]
